Repository Nefariusek/CodersCamp2021.Project.JavaScript, pull requests merged in 2021-12, with the labels that each got.

#53 Enhancement/issue 52
  src/views/MainPage/MainPage.css
  src/views/MainPage/MainPage.js
Labels: enhancement

#55 Changes in css which fix the bug with koala
  src/components/Button/Button.css
  src/views/MainPage/MainPage.css
Labels: bug, Sprint_4

#60 Feature/issue 12
  src/api/FactsController.js
  src/components/Bubble/Bubble.css
  src/components/Bubble/Bubble.js
  src/model/Fact.js
  src/model/ImageFact.js
  src/style.css
  src/views/MainPage/MainPage.css
  src/views/MainPage/MainPage.js
Labels: feature, Sprint_4

#71 Feature/issue 20
  src/components/Bubble/Bubble.js
  src/components/router/Router.js
  src/model/Fact.js
  src/model/ImageFact.js
  src/style.css
  src/views/CreditsPage/CreditsPage.css
  src/views/CreditsPage/CreditsPage.js
  src/views/MainPage/MainPage.css
  src/views/MainPage/MainPage.js
Labels: feature, Sprint_4

#82 Feature/issue 72
  README.md
  public/adoption-bird.jpg
  public/adoption-cat.jpg
  public/adoption-dog.jpg
  public/bird.png
  src/components/router/Router.js
  src/style.css
  src/views/AdoptionPage/AdoptionPage.css
  src/views/AdoptionPage/AdoptionPage.js
Labels: feature, Sprint_5

#86 improvements following eslint suggestions
  .eslintrc
  src/api/FactsController.js
  src/components/Bubble/Bubble.js
  src/model/Fact.js
  src/model/ImageFact.js
  src/views/CreditsPage/CreditsPage.js
  src/views/MainPage/MainPage.js
Labels: enhancement, Sprint_5

#66 Feature/issue 50
  src/views/Leaderboard/Leaderboard.css
  src/views/Leaderboard/Leaderboard.js
  src/views/ScorePage/ScorePage.css
  src/views/ScorePage/ScorePage.js
Labels: feature, Sprint_4
