Repository Nefariusek/CodersCamp2021.Project.JavaScript, pull requests merged in 2022-01, with the labels that each got.

#90 Bug/issue 79
  src/api/FactsController.js
  src/components/Bubble/Bubble.css
  src/components/Bubble/Bubble.js
  src/views/MainPage/MainPage.js
Labels: bug, Sprint_5

#92 [hotfix] Making the adoption bubble behave like the fact bubble
  src/components/Bubble/Bubble.css
  src/views/MainPage/MainPage.js
Labels: Sprint_5

#94 Enhancement/issue 73
  src/api/getQuizQuestions.js
  src/components/Answer/Answer.js
  src/components/Dropdown/Dropdown.css
  src/components/Dropdown/Dropdown.js
  src/components/RangeSelect/RangeSelect.css
  src/components/RangeSelect/RangeSelect.js
  src/components/ScoreFilter/ScoreFilter.css
  src/components/ScoreFilter/ScoreFilter.js
  src/model/randomizer.js
  src/views/Leaderboard/Leaderboard.css
  src/views/Leaderboard/Leaderboard.js
  src/views/ScorePage/ScorePage.css
  src/views/ScorePage/ScorePage.js
  src/views/quiz-settings/quiz-settings.js
Labels: help wanted

#93 Feature/issue 62
  src/components/Answer/Answer.js
  src/views/QuizView/quizView.css
  src/views/QuizView/quizView.js
Labels: Sprint_4

#98 Fixing paths and urls for the production version
  src/views/AdoptionPage/AdoptionPage.css
  src/views/AdoptionPage/AdoptionPage.js
  src/views/CreditsPage/CreditsPage.js
  src/views/MainPage/MainPage.js
Labels: bug, Sprint_5

#99 Fixing paths for the production version
  src/views/AdoptionPage/AdoptionPage.js
  src/views/CreditsPage/CreditsPage.js
  src/views/MainPage/MainPage.js
Labels: bug, Sprint_5
